#!/bin/sh
#PBS -N COHP
#PBS -q avx512op
#PBS -l nodes=1:ppn=64

NPROCS=`cat $PBS_NODEFILE|wc -l`
cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=80
#module purge
/home/bogeun1007/bin/lobster/lobster-5.1.1 >& log
